from random import random
from best_n import find_best, find_best_with_sort
import time

if __name__ == '__main__':
    number_of_elements = 100000

    autogenerated_collection = [20*random() for x in range(number_of_elements)]

    print("Testiramo performanse pronalaženja prvih 10 elemenata kolekcije.")
    print("Poredimo performanse algoritma sortiranja 'selection sort' sa pronalaženjem samo 10 najboljih.")
    print("Testiranje se obavlja nad kolekcijom od", number_of_elements, "elemenata.")
    print("Molim za strpljenje... ")
    start_sort = time.time()
    find_best_with_sort(autogenerated_collection, 10)
    end_sort = time.time()

    print("Selection sort:", end_sort - start_sort)

    start_top = time.time()
    find_best(autogenerated_collection, 10)
    end_top = time.time()
    print("Top 10:", end_top - start_top)